### ISSUE TITLE
IndexError in library.py

### ISSUE THREAD

**Issue by MrSurly** [OzymandiasTheGreat/mopidy-ytmusic#21]
Seeing this a lot in `/var/log/daemon.log`

```eb  8 19:51:22 controller mopidy[13822]: ERROR    [Core-10] mopidy.core.library YTMusicBackend backend caused an exception.
Feb  8 19:51:22 controller mopidy[13822]: Traceback (most recent call last):
Feb  8 19:51:22 controller mopidy[13822]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
Feb  8 19:51:22 controller mopidy[13822]:     yield
Feb  8 19:51:22 controller mopidy[13822]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 217, in lookup
Feb  8 19:51:22 controller mopidy[13822]:     result = future.get()
Feb  8 19:51:22 controller mopidy[13822]:   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
Feb  8 19:51:22 controller mopidy[13822]:     _compat.reraise(*self._data['exc_info'])
Feb  8 19:51:22 controller mopidy[13822]:   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
Feb  8 19:51:22 controller mopidy[13822]:     raise value
Feb  8 19:51:22 controller mopidy[13822]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Feb  8 19:51:22 controller mopidy[13822]:     response = self._handle_receive(envelope.message)
Feb  8 19:51:22 controller mopidy[13822]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Feb  8 19:51:22 controller mopidy[13822]:     return callee(*message.args, **message.kwargs)
Feb  8 19:51:22 controller mopidy[13822]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/library.py", line 411, in lookup
Feb  8 19:51:22 controller mopidy[13822]:     bId, upload = parse_uri(uri)
Feb  8 19:51:22 controller mopidy[13822]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/library.py", line 1135, in parse_uri
Feb  8 19:51:22 controller mopidy[13822]:     bId = components[2]
Feb  8 19:51:22 controller mopidy[13822]: IndexError: list index out of range
```

**Comment by impliedchaos** [comment]
I just ran into this yesterday myself.  I fixed it in Mopidy-Bandcamp, but haven't had a chance to fix it here yet.  

This is from Iris.  I don't know why, but it makes the backend do lookup()s on browser entries.  It's weird, and the only client (that I've seen) that does this.   I'll get it patched shortly.

**Comment by rebernet** [comment]
I have the same problem. Was just trying out your extension. Can you create a new release with your fix?

**Comment by impliedchaos** [comment]
Yeah, I'm sorry, I kinda forgot.  I'll create the release here on github, and then Tomas will likely create the pypi release a bit later.

**Comment by OzymandiasTheGreat** [comment]
Sorry for the delay, it's on PyPI now.
