### ISSUE TITLE
Library doesn't work

### ISSUE THREAD

**Issue by SkyLeite** [OzymandiasTheGreat/mopidy-ytmusic#26]
I get the following error when trying to access my library:

```
ERROR    2021-03-05 11:03:21,093 [96198:YTMusicBackend-7] mopidy_ytmusic
  YTMusic failed getting artists from library
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mopidy_ytmusic/library.py", line 475, in get_distinct
    library = self.backend.api.get_library_artists(
  File "/home/rodrigo/.local/lib/python3.9/site-packages/ytmusicapi/mixins/library.py", line 148, in get_library_artists
    self._check_auth()
  File "/home/rodrigo/.local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 134, in _check_auth
    raise Exception("Please provide authentication before using this function")
Exception: Please provide authentication before using this function
```

As far as I can tell, I did the setup process successfully. My mopidy config file points to my auth.json file correctly, and ytmusic is set to enabled.

**Comment by impliedchaos** [comment]
The best I can tell is that the authentication procedure didn't work.   All I can suggest is to run the `gmusic ytmusic reauth` to try again.

**Comment by SkyLeite** [comment]
Library works now.
