### ISSUE TITLE
Solved libffi issue on Raspberry Pi 4

### ISSUE THREAD

**Issue by 1kc** [OzymandiasTheGreat/mopidy-ytmusic#29]
Device: Raspberry Pi 4
OS: Ubuntu 20.04 64 bit

I had this error in mopidy when I installed via `sudo python3 -m pip install Mopidy-YTMusic`.

```
ERROR    2021-04-26 02:39:22,214 [21325:Thread-4] mopidy_ytmusic
  YTMusic failed to load auto playlists
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mopidy_ytmusic/backend.py", line 126, in _get_auto_playlists
    response = self.api._send_request("browse", {})
  File "/usr/local/lib/python3.8/dist-packages/ytmusicapi/ytmusic.py", line 120, in _send_request
    response = self._session.post(base_url + endpoint + params + additionalParams,
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 348, in connect
    self.ssl_context = create_urllib3_context(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 286, in create_urllib3_context
    context.verify_mode = cert_reqs
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 438, in verify_mode
    self._ctx.set_verify(_stdlib_to_openssl_verify[value], _verify_callback)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1103, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 332, in __init__
    self.callback = _ffi.callback(
SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
```

What fixed it was:
Git cloning the project and `sudo python3 setup.py install` in mopidy-ytmusic

Just letting anyone who might have ran into this issue know.

Thanks for the project!

**Comment by impliedchaos** [comment]
Good find!

I wonder if doing: `sudo python3 -m pip install --no-binary Mopidy-YTMusic` would have also solved it by forcing pip to install from the source package?

**Comment by 1kc** [comment]
`sudo python3 -m pip install --no-binary Mopidy-YTMusic Mopidy-YTMusic` seems to work.
