### ISSUE TITLE
Invalid Header Name

### ISSUE THREAD

**Issue by fahcsim** [OzymandiasTheGreat/mopidy-ytmusic#34]
I can't seem to get this extension to fetch any content from my YT music premium account. I am running as a service on raspbian on a pi 3b+, have recreated the auth.json several times, but seem to be getting errors possibly related to an invalid header name

Here's a snippet of the logs that looked relevant. This same thing is happening for playlists, artists etc

`Aug 08 21:48:40 octopi mopidy[30483]: ERROR    [YTMusicBackend-3] mopidy_ytmusic YTMusic failed getting listening history
Aug 08 21:48:40 octopi mopidy[30483]: Traceback (most recent call last):
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/library.py", line 169, in browse
Aug 08 21:48:40 octopi mopidy[30483]:     res = self.backend.api.get_history()
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/mixins/library.py", line 198, in get_history
Aug 08 21:48:40 octopi mopidy[30483]:     response = self._send_request(endpoint, body)
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/ytmusic.py", line 127, in _send_request
Aug 08 21:48:40 octopi mopidy[30483]:     proxies=self.proxies)
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 590, in post
Aug 08 21:48:40 octopi mopidy[30483]:     return self.request('POST', url, data=data, json=json, **kwargs)
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 542, in request
Aug 08 21:48:40 octopi mopidy[30483]:     resp = self.send(prep, **send_kwargs)
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 655, in send
Aug 08 21:48:40 octopi mopidy[30483]:     r = adapter.send(request, **kwargs)
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
Aug 08 21:48:40 octopi mopidy[30483]:     timeout=timeout
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
Aug 08 21:48:40 octopi mopidy[30483]:     chunked=chunked)
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
Aug 08 21:48:40 octopi mopidy[30483]:     conn.request(method, url, **httplib_request_kw)
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/lib/python3.7/http/client.py", line 1244, in request
Aug 08 21:48:40 octopi mopidy[30483]:     self._send_request(method, url, body, headers, encode_chunked)
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/lib/python3.7/http/client.py", line 1285, in _send_request
Aug 08 21:48:40 octopi mopidy[30483]:     self.putheader(hdr, value)
Aug 08 21:48:40 octopi mopidy[30483]:   File "/usr/lib/python3.7/http/client.py", line 1212, in putheader
Aug 08 21:48:40 octopi mopidy[30483]:     raise ValueError('Invalid header name %r' % (header,))
Aug 08 21:48:40 octopi mopidy[30483]: ValueError: Invalid header name b':authority'`

**Comment by fahcsim** [comment]
My apologies, this was my error. I had copied the first few lines that started with a colon. Once I removed those and restarted mopidy it's working fine.

In case anyone runs into this in the future, these are the lines that needed to be removed:

`:authority: music.youtube.com
:method: POST
:path: 
:scheme: https`
