### ISSUE TITLE
Failing to load albums

### ISSUE THREAD

**Issue by tepiloxtl** [OzymandiasTheGreat/mopidy-ytmusic#37]
It was working just yesterday. Tried to upgrade to latest mopidy-ytmusic, but Im already running latest. Im trying through musicbox and iris frontends, it loads album list when I search for it, but then fails to load album contents, and throws this in console
```
YTMusic failed getting tracks for album "MPREb_kTLtO7HmJoO"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/library.py", line 436, in lookup
    res = self.backend.api.get_album(bId)
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/mixins/browsing.py", line 482, in get_album
    album = parse_album_header(response)
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/parsers/albums.py", line 28, in parse_album_header
    album['audioPlaylistId'] = nav(toplevel, [0, 'buttonRenderer'] + NAVIGATION_PLAYLIST_ID)
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/parsers/utils.py", line 155, in nav
    raise err
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/parsers/utils.py", line 149, in nav
    root = root[k]
KeyError: 'watchEndpoint'
```

**Comment by impliedchaos** [comment]
Just pushed the v0.3.1 release that should fix this.  Youtube made a lot of backend changes and I had to update to the newest version of ytmusicapi.  Sadly, some of the uploaded music stuff is now broken, and I don't have a chance right now to investigate further.  I'll try looking again next weekend.
