### ISSUE TITLE
Artist or album not working most of the times

### ISSUE THREAD

**Issue by shameerariff** [OzymandiasTheGreat/mopidy-ytmusic#39]
Search page list artist, albums, and tracks, whereas while clicking the album or artist, very few proceed further, but most are failed with the following error logs. 
```
Oct 28 10:35:06 BhoomBox mopidy[8705]: ERROR    2021-10-28 10:35:06,964 [8705:YTMusicBackend-4] mopidy_ytmusic
Oct 28 10:35:06 BhoomBox mopidy[8705]:   YTMusic failed parsing artist Khalil Ar Rahman
Oct 28 10:35:06 BhoomBox mopidy[8705]: Traceback (most recent call last):
Oct 28 10:35:06 BhoomBox mopidy[8705]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/library.py", line 1025, in parseSearch
Oct 28 10:35:06 BhoomBox mopidy[8705]:     artistq = self.backend.api.get_artist(result["browseId"])
Oct 28 10:35:06 BhoomBox mopidy[8705]:   File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/mixins/browsing.py", line 274, in get_artist
Oct 28 10:35:06 BhoomBox mopidy[8705]:     results = nav(response, SINGLE_COLUMN_TAB + SECTION_LIST)
Oct 28 10:35:06 BhoomBox mopidy[8705]:   File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/parsers/utils.py", line 155, in nav
Oct 28 10:35:06 BhoomBox mopidy[8705]:     raise err
Oct 28 10:35:06 BhoomBox mopidy[8705]:   File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/parsers/utils.py", line 149, in nav
Oct 28 10:35:06 BhoomBox mopidy[8705]:     root = root[k]
Oct 28 10:35:06 BhoomBox mopidy[8705]: KeyError: 'content'
Oct 28 10:35:13 BhoomBox mopidy[8705]: ERROR    2021-10-28 10:35:13,229 [8705:YTMusicBackend-4] mopidy_ytmusic
Oct 28 10:35:13 BhoomBox mopidy[8705]:   YTMusic failed getting tracks for album "MPREb_aBM8bH2LWzL"
Oct 28 10:35:13 BhoomBox mopidy[8705]: Traceback (most recent call last):
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/library.py", line 437, in lookup
Oct 28 10:35:13 BhoomBox mopidy[8705]:     tracks = self.albumToTracks(res, bId)
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/library.py", line 904, in albumToTracks
Oct 28 10:35:13 BhoomBox mopidy[8705]:     songartists = [Artist(name=song["artists"])]
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/lib/python3/dist-packages/mopidy/models/immutable.py", line 159, in __call__
Oct 28 10:35:13 BhoomBox mopidy[8705]:     instance = super().__call__(*args, **kwargs)
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/lib/python3/dist-packages/mopidy/models/immutable.py", line 35, in __init__
Oct 28 10:35:13 BhoomBox mopidy[8705]:     self._set_field(key, value)
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/lib/python3/dist-packages/mopidy/models/immutable.py", line 188, in _set_field
Oct 28 10:35:13 BhoomBox mopidy[8705]:     object.__setattr__(self, name, value)
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/lib/python3/dist-packages/mopidy/models/fields.py", line 50, in __set__
Oct 28 10:35:13 BhoomBox mopidy[8705]:     value = self.validate(value)
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/lib/python3/dist-packages/mopidy/models/fields.py", line 35, in validate
Oct 28 10:35:13 BhoomBox mopidy[8705]:     f"Expected {self._name} to be a {self._type}, not {value!r}"
Oct 28 10:35:13 BhoomBox mopidy[8705]: TypeError: Expected name to be a <class 'str'>, not [{'name': 'Hiphop Tamizha', 'id': 'UC8_JHp4od83YimfxGWqrefQ'}, {'name': 'Deepak', 'id': 'UCvU4z0aC61RzZWlo5OdxrHQ'}]
Oct 28 10:35:13 BhoomBox mopidy[8705]: ERROR    2021-10-28 10:35:13,375 [8705:YTMusicBackend-4] mopidy_ytmusic
Oct 28 10:35:13 BhoomBox mopidy[8705]:   YTMusic failed getting tracks for album "MPREb_aBM8bH2LWzL"
Oct 28 10:35:13 BhoomBox mopidy[8705]: Traceback (most recent call last):
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/library.py", line 437, in lookup
Oct 28 10:35:13 BhoomBox mopidy[8705]:     tracks = self.albumToTracks(res, bId)
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/library.py", line 904, in albumToTracks
Oct 28 10:35:13 BhoomBox mopidy[8705]:     songartists = [Artist(name=song["artists"])]
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/lib/python3/dist-packages/mopidy/models/immutable.py", line 159, in __call__
Oct 28 10:35:13 BhoomBox mopidy[8705]:     instance = super().__call__(*args, **kwargs)
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/lib/python3/dist-packages/mopidy/models/immutable.py", line 35, in __init__
Oct 28 10:35:13 BhoomBox mopidy[8705]:     self._set_field(key, value)
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/lib/python3/dist-packages/mopidy/models/immutable.py", line 188, in _set_field
Oct 28 10:35:13 BhoomBox mopidy[8705]:     object.__setattr__(self, name, value)
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/lib/python3/dist-packages/mopidy/models/fields.py", line 50, in __set__
Oct 28 10:35:13 BhoomBox mopidy[8705]:     value = self.validate(value)
Oct 28 10:35:13 BhoomBox mopidy[8705]:   File "/usr/lib/python3/dist-packages/mopidy/models/fields.py", line 35, in validate
Oct 28 10:35:13 BhoomBox mopidy[8705]:     f"Expected {self._name} to be a {self._type}, not {value!r}"
Oct 28 10:35:13 BhoomBox mopidy[8705]: TypeError: Expected name to be a <class 'str'>, not [{'name': 'Hiphop Tamizha', 'id': 'UC8_JHp4od83YimfxGWqrefQ'}, {'name': 'Deepak', 'id': 'UCvU4z0aC61RzZWlo5OdxrHQ'}]
Oct 28 10:35:17 BhoomBox mopidy[8705]: INFO     2021-10-28 10:35:17,034 [8705:MpdSession-71] mopidy_mpd.session
Oct 28 10:35:17 BhoomBox mopidy[8705]:   New MPD connection from [::ffff:127.0.0.1]:34762

```
It is the common search page with no issue
![Screenshot_2021-10-28_10-46-01](https://user-images.githubusercontent.com/10761850/139191544-038192a1-9cda-4f82-a18a-3335d156a230.png)
The following shows the issue on clicking any album or artist
![Screenshot_2021-10-28_10-45-45](https://user-images.githubusercontent.com/10761850/139191607-4caedd92-c999-4cc3-88f7-6958ffbab215.png)

I tried upgraded and reinstalling ytmusic, but no use.

**Comment by adrhc** [comment]
I hope the relate log below to help.

Nov 22 18:38:49 mopidy[230606]: ERROR    [HttpServer] tornado.application Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f12547436d0>>, <Task finished name='Task-8775' coro=<IrisCore.update_snapcast_meta() done, defined at /usr/local/lib/python3.9/dist-packages/mopidy_iris/core.py:1159> exception=KeyError('artists')>)
Nov 22 18:38:49 mopidy[230606]: Traceback (most recent call last):
Nov 22 18:38:49 mopidy[230606]:   File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 741, in _run_callback
Nov 22 18:38:49 mopidy[230606]:     ret = callback()
Nov 22 18:38:49 mopidy[230606]:   File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 765, in _discard_future_result
Nov 22 18:38:49 mopidy[230606]:     future.result()
Nov 22 18:38:49 mopidy[230606]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_iris/core.py", line 1176, in update_snapcast_meta
Nov 22 18:38:49 mopidy[230606]:     meta["artists"] = track["artists"]
Nov 22 18:38:49 mopidy[230606]: KeyError: 'artists'
Nov 22 18:38:49 mopidy[230606]: WARNING  [ScrobblerFrontend-26] mopidy_scrobbler.frontend Error submitting playing
