### ISSUE TITLE
mopidy_ytmusic YTMusic found forbidden URL. Updating player URL now.

### ISSUE THREAD

**Issue by adrhc** [OzymandiasTheGreat/mopidy-ytmusic#42]
Hi, some of the songs in my Youtube Music “Likes” playlist have the issue below; all of them played fine yesterday. I have a free subscription/account.

The song is [https://music.youtube.com/watch?v=rP9Z5Pc8cRM&feature=share](https://music.youtube.com/watch?v=rP9Z5Pc8cRM&feature=share) - (existing) link copied using Youtube Music from my "Likes" playlist; I tried to play it with mopidy (using Iris) and I've got the error below; I can though play it from Youtube Music.

This on the other hand will play fine with mopidy (+ Iris): [https://music.youtube.com/watch?v=fcaWN3ZJnhs&feature=share](https://music.youtube.com/watch?v=fcaWN3ZJnhs&feature=share).

```log
Nov 22 19:07:09 mopidy[230606]: INFO     [YTMusicBackend-3] mopidy_ytmusic YTMusic Found AUDIO_QUALITY_MEDIUM stream with 150608 bitrate for rP9Z5Pc8cRM
Nov 22 19:07:09 mopidy[230606]: ERROR    [YTMusicBackend-3] mopidy_ytmusic YTMusic found forbidden URL. Updating player URL now.
Nov 22 19:07:09 mopidy[230606]: WARNING  [Core-18] mopidy.core.tracklist Track is not playable: ytmusic:track:rP9Z5Pc8cRM
Nov 22 19:07:13 mopidy[230606]: ERROR    [HttpServer] tornado.application Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f12547436d0>>, <Task finished name='Task-9182' coro=<IrisCore.update_snapcast_meta() done, defined at /usr/local/lib/python3.9/dist-packages/mopidy_iris/core.py:1159> exception=KeyError('artists')>)
Nov 22 19:07:13 mopidy[230606]: Traceback (most recent call last):
Nov 22 19:07:13 mopidy[230606]:   File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 741, in _run_callback
Nov 22 19:07:13 mopidy[230606]:     ret = callback()
Nov 22 19:07:13 mopidy[230606]:   File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 765, in _discard_future_result
Nov 22 19:07:13 mopidy[230606]:     future.result()
Nov 22 19:07:13 mopidy[230606]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_iris/core.py", line 1176, in update_snapcast_meta
Nov 22 19:07:13 mopidy[230606]:     meta["artists"] = track["artists"]
Nov 22 19:07:13 mopidy[230606]: KeyError: 'artists'
Nov 22 19:07:13 mopidy[230606]: WARNING  [ScrobblerFrontend-26] mopidy_scrobbler.frontend Error submitting playing track to Last.fm: Invalid parameters - Your request is missing a required parameter
```

**Comment by impliedchaos** [comment]
Thanks, I'll look into this ASAP.

**Comment by impliedchaos** [comment]
@adrhc, can you try again now?  I'm hoping this is caused by the same pytube issue as #41 which isn't happening right now.

**Comment by adrhc** [comment]
aha, let me check

**Comment by CastleCaptain** [comment]
I am getting this error as well. My system is running the latest pytube and ytmusicapi if that is of concern. Cipher.py has been updated to include a 3rd fun ction name definition as suggested in some other posts. What else can I do to resolve this?
