### ISSUE TITLE
Cannot list artist's songs

### ISSUE THREAD

**Issue by eschava** [OzymandiasTheGreat/mopidy-ytmusic#5]
I see the correct list of artists but when I try to see his songs I get the next error:

INFO     2020-12-13 10:11:56,420 [19976:YTMusicBackend-6] mopidy_ytmusic
  YTMusic browsing uri "ytm:artist?id=MPLAUCRbMcMQeSFVvsyEuOn7uAKQ&upload=false"
ERROR    2020-12-13 10:11:56,822 [19976:Core-7] mopidy.core.library
  YTMusicBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/backend.py", line 483, in browse
    res = API.get_artist(id_)
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/mixins/browsing.py", line 191, in get_artist
    header = response['header']['musicImmersiveHeaderRenderer']
KeyError: 'musicImmersiveHeaderRenderer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 114, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/local/lib/python3.7/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python3.7/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/backend.py", line 491, in browse
    logger.exception("YTMusic failed getting tracks for artist \"%s\"", res["name"])
UnboundLocalError: local variable 'res' referenced before assignment

**Comment by eschava** [comment]
Trace for the latest version is 

ERROR    2020-12-13 10:50:45,746 [21742:YTMusicBackend-6] mopidy_ytmusic
  YTMusic failed getting tracks for artist "MPLAUCwWtKZD4xNVpEHndNxYu51g"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/backend.py", line 486, in browse
    res = API.get_artist(id_)
  File "/home/pi/.local/lib/python3.7/site-packages/ytmusicapi/mixins/browsing.py", line 206, in get_artist
    header = response['header']['musicImmersiveHeaderRenderer']
KeyError: 'musicImmersiveHeaderRenderer'

**Comment by eschava** [comment]
I see that it is related to the ytmusicapi library and is listed there already
https://github.com/sigma67/ytmusicapi/issues/117
