### ISSUE TITLE
Suddenly stopped working. Can search, but can´t  play.

### ISSUE THREAD

**Issue by herkow** [OzymandiasTheGreat/mopidy-ytmusic#59]
Last night was working perfectly, and this morning, unable to play.

```
jun 04 12:20:36 MEDIA systemd[1]: Starting Mopidy music server...
jun 04 12:20:36 MEDIA systemd[1]: Started Mopidy music server.
jun 04 12:20:37 MEDIA mopidy[797]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.3.0
jun 04 12:20:37 MEDIA mopidy[797]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
jun 04 12:20:37 MEDIA mopidy[797]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
jun 04 12:20:37 MEDIA mopidy[797]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
jun 04 12:20:37 MEDIA mopidy[797]: INFO     [MainThread] mopidy.config Loading config from command line options
jun 04 12:20:37 MEDIA mopidy[797]: INFO     [MainThread] mopidy.__main__ Enabled extensions: http, musicbox_webclient, stream, youtube, m3u, file, ytmusic, softwaremixer
jun 04 12:20:37 MEDIA mopidy[797]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
jun 04 12:20:38 MEDIA mopidy[797]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
jun 04 12:20:38 MEDIA mopidy[797]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
jun 04 12:20:38 MEDIA mopidy[797]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: YTMusicBackend, YouTubeBackend, FileBackend, M3UBackend, StreamBackend
jun 04 12:20:38 MEDIA mopidy[797]: INFO     [YouTubeBackend-6] mopidy_youtube file caching not enabled
jun 04 12:20:38 MEDIA mopidy[797]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "autoaudiosink"
jun 04 12:20:39 MEDIA mopidy[797]: INFO     [YouTubeBackend-6] mopidy_youtube YouTube API key verified
jun 04 12:20:39 MEDIA mopidy[797]: INFO     [MainThread] mopidy.commands Starting Mopidy core
jun 04 12:20:39 MEDIA mopidy[797]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: YTMusicScrobbleFE, YouTubeAutoplayer, YouTubeCoreListener, HttpFrontend
jun 04 12:20:39 MEDIA mopidy[797]: INFO     [HttpFrontend-15] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
jun 04 12:20:39 MEDIA mopidy[797]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
jun 04 12:20:40 MEDIA mopidy[797]: Exception in thread Thread-5:
jun 04 12:20:40 MEDIA mopidy[797]: Traceback (most recent call last):
jun 04 12:20:40 MEDIA mopidy[797]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
jun 04 12:20:40 MEDIA mopidy[797]:     self.run()
jun 04 12:20:40 MEDIA mopidy[797]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_ytmusic/repeating_timer.py", line 18, in run
jun 04 12:20:40 MEDIA mopidy[797]:     self._method()
jun 04 12:20:40 MEDIA mopidy[797]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_ytmusic/backend.py", line 99, in _refresh_youtube_player
jun 04 12:20:40 MEDIA mopidy[797]:     self.playback.update_cipher(playerurl=url)
jun 04 12:20:40 MEDIA mopidy[797]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_ytmusic/playback.py", line 25, in update_cipher
jun 04 12:20:40 MEDIA mopidy[797]:     self.PyTubeCipher = Cipher(js=response.text)
jun 04 12:20:40 MEDIA mopidy[797]:   File "/usr/local/lib/python3.9/dist-packages/pytube/cipher.py", line 33, in __init__
jun 04 12:20:40 MEDIA mopidy[797]:     raise RegexMatchError(
jun 04 12:20:40 MEDIA mopidy[797]: pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W
jun 04 12:20:41 MEDIA mopidy[797]: INFO     [Thread-4] mopidy_ytmusic YTMusic loaded 20 auto playlists sections
jun 04 12:20:41 MEDIA mopidy[797]: INFO     [Thread-4] mopidy_ytmusic YTMusic Auto Playlists refreshed in 3.11s
jun 04 12:23:59 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:23:59 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:uqSnMf3nN9Q
jun 04 12:23:59 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:23:59 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:Dku4Pj3DijE
jun 04 12:24:00 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:00 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:H9V-3-e4MzI
jun 04 12:24:00 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:00 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:UcTuUiNaNac
jun 04 12:24:00 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:00 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:petVwbXFgWg
jun 04 12:24:00 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:00 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:adJ6XQ_glpo
jun 04 12:24:00 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:00 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:PqoiJGPiuig
jun 04 12:24:00 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:00 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:dWcTD5UhUIk
jun 04 12:24:00 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:00 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:aA7ptpxeVxU
jun 04 12:24:01 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:01 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:MoFBBRE-eIk
jun 04 12:24:01 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:01 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:vjf_ONz5CtA
jun 04 12:24:01 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:01 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:ZFXKJEPbQfk
jun 04 12:24:06 MEDIA mopidy[797]: ERROR    [YTMusicBackend-3] mopidy_ytmusic translate_uri error "'NoneType' object has no attribute 'get_signature'"
jun 04 12:24:06 MEDIA mopidy[797]: WARNING  [Core-10] mopidy.core.tracklist Track is not playable: ytmusic:track:ZFXKJEPbQfk 
```

**Comment by rebernet** [comment]
Have you checked this issue [mopidy-ytmusic/issues/41](https://github.com/OzymandiasTheGreat/mopidy-ytmusic/issues/41)? Editing pytube sources accordingly fixed the problem for me (a not very convenient solution though).

**Comment by herkow** [comment]
OK, after reading the log and seeing that the problem was RegexMatchError I decided to fix it manually, but it didn't work. I was using the alternative package, not the official pytube... And then I thought: what if I install the official pyutbe and fix the line mannually? So, after installing the offcial one, and fixed the line with ^\$*\w+\W, it's now working perfectly.
