### ISSUE TITLE
Not working after reauth

### ISSUE THREAD

**Issue by herkow** [OzymandiasTheGreat/mopidy-ytmusic#60]
Was working ok, then after a `sudo mopidyctl ytmusic reauth` stopped working.

```
jun 29 16:17:10 MEDIA systemd[1]: Starting Mopidy music server...
jun 29 16:17:10 MEDIA systemd[1]: Started Mopidy music server.
jun 29 16:18:03 MEDIA mopidy[608]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.3.0
jun 29 16:18:03 MEDIA mopidy[608]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
jun 29 16:18:03 MEDIA mopidy[608]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
jun 29 16:18:03 MEDIA mopidy[608]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
jun 29 16:18:03 MEDIA mopidy[608]: INFO     [MainThread] mopidy.config Loading config from command line options
jun 29 16:18:05 MEDIA mopidy[608]: INFO     [MainThread] mopidy.__main__ Enabled extensions: http, m3u, musicbox_webclient, stream, softwaremixer, file, ytmusic, youtube
jun 29 16:18:05 MEDIA mopidy[608]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
jun 29 16:18:08 MEDIA mopidy[608]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
jun 29 16:18:08 MEDIA mopidy[608]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
jun 29 16:18:08 MEDIA mopidy[608]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: YTMusicBackend, YouTubeBackend, FileBackend, M3UBackend, StreamBackend
jun 29 16:18:09 MEDIA mopidy[608]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "autoaudiosink"
jun 29 16:18:09 MEDIA mopidy[608]: ERROR    [MainThread] mopidy.commands Got un-handled exception from YTMusicBackend
jun 29 16:18:09 MEDIA mopidy[608]: Traceback (most recent call last):
jun 29 16:18:09 MEDIA mopidy[608]:   File "/usr/local/lib/python3.9/dist-packages/ytmusicapi/ytmusic.py", line 124, in __init__
jun 29 16:18:09 MEDIA mopidy[608]:     self.sapisid = sapisid_from_cookie(cookie)
jun 29 16:18:09 MEDIA mopidy[608]:   File "/usr/local/lib/python3.9/dist-packages/ytmusicapi/helpers.py", line 82, in sapisid_from_cookie
jun 29 16:18:09 MEDIA mopidy[608]:     return cookie['__Secure-3PAPISID'].value
jun 29 16:18:09 MEDIA mopidy[608]: KeyError: '__Secure-3PAPISID'
jun 29 16:18:09 MEDIA mopidy[608]: During handling of the above exception, another exception occurred:
jun 29 16:18:09 MEDIA mopidy[608]: Traceback (most recent call last):
jun 29 16:18:09 MEDIA mopidy[608]:   File "/usr/lib/python3/dist-packages/mopidy/commands.py", line 248, in _actor_error_handling
jun 29 16:18:09 MEDIA mopidy[608]:     yield
jun 29 16:18:09 MEDIA mopidy[608]:   File "/usr/lib/python3/dist-packages/mopidy/commands.py", line 412, in start_backends
jun 29 16:18:09 MEDIA mopidy[608]:     backend = backend_class.start(
jun 29 16:18:09 MEDIA mopidy[608]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 91, in start
jun 29 16:18:09 MEDIA mopidy[608]:     obj = cls(*args, **kwargs)
jun 29 16:18:09 MEDIA mopidy[608]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_ytmusic/backend.py", line 65, in __init__
jun 29 16:18:09 MEDIA mopidy[608]:     self.api = YTMusic(self._ytmusicapi_auth_json)
jun 29 16:18:09 MEDIA mopidy[608]:   File "/usr/local/lib/python3.9/dist-packages/ytmusicapi/ytmusic.py", line 126, in __init__
jun 29 16:18:09 MEDIA mopidy[608]:     raise Exception("Your cookie is missing the required value __Secure-3PAPISID")
jun 29 16:18:09 MEDIA mopidy[608]: Exception: Your cookie is missing the required value __Secure-3PAPISID
jun 29 16:18:09 MEDIA mopidy[608]: INFO     [YouTubeBackend-3] mopidy_youtube file caching not enabled
jun 29 16:18:10 MEDIA mopidy[608]: INFO     [YouTubeBackend-3] mopidy_youtube YouTube API key verified
jun 29 16:18:10 MEDIA mopidy[608]: INFO     [MainThread] mopidy.commands Starting Mopidy core
jun 29 16:18:10 MEDIA mopidy[608]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: YTMusicScrobbleFE, YouTubeAutoplayer, YouTubeCoreListener, HttpFrontend
jun 29 16:18:10 MEDIA mopidy[608]: INFO     [HttpFrontend-12] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
jun 29 16:18:10 MEDIA mopidy[608]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
```

**Comment by herkow** [comment]
After a reload on the YoutubeMusic site, correct  __Secure-3PAPISID value was obtained.
