### ISSUE TITLE
mopidy_ytmusic YTMusic failed getting liked songs, KeyError singleColumnBrowseResultsRenderer

### ISSUE THREAD

**Issue by adrhc** [OzymandiasTheGreat/mopidy-ytmusic#81]
The YouTube Music Liked Songs is empty:

```
Jun 21 11:40:13 mopidy[10911]: ERROR    [YTMusicBackend-15] mopidy_ytmusic YTMusic failed getting liked songs
Jun 21 11:40:13 mopidy[10911]: Traceback (most recent call last):
Jun 21 11:40:13 mopidy[10911]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_ytmusic/library.py", line 159, in browse
Jun 21 11:40:13 mopidy[10911]:     res = self.backend.api.get_liked_songs(
Jun 21 11:40:13 mopidy[10911]:   File "/usr/local/lib/python3.9/dist-packages/ytmusicapi/mixins/library.py", line 194, in get_liked_songs
Jun 21 11:40:13 mopidy[10911]:     return self.get_playlist('LM', limit)
Jun 21 11:40:13 mopidy[10911]:   File "/usr/local/lib/python3.9/dist-packages/ytmusicapi/mixins/playlists.py", line 110, in get_playlist
Jun 21 11:40:13 mopidy[10911]:     results = nav(response,
Jun 21 11:40:13 mopidy[10911]:   File "/usr/local/lib/python3.9/dist-packages/ytmusicapi/navigation.py", line 81, in nav
Jun 21 11:40:13 mopidy[10911]:     raise err
Jun 21 11:40:13 mopidy[10911]:   File "/usr/local/lib/python3.9/dist-packages/ytmusicapi/navigation.py", line 75, in nav
Jun 21 11:40:13 mopidy[10911]:     root = root[k]
Jun 21 11:40:13 mopidy[10911]: KeyError: 'singleColumnBrowseResultsRenderer'

mopidy-ytmusic==0.3.8
  - Mopidy [required: >=3,<4, installed: 3.3.0]
    - Pykka [required: >=2.0.1, installed: 3.0.2]
    - requests [required: >=2.0, installed: 2.31.0]
      - certifi [required: >=2017.4.17, installed: 2022.5.18]
      - charset-normalizer [required: >=2,<4, installed: 2.0.12]
      - idna [required: >=2.5,<4, installed: 3.3]
      - urllib3 [required: >=1.21.1,<3, installed: 2.1.0]
    - setuptools [required: Any, installed: 62.3.2]
    - tornado [required: >=4.4, installed: 6.1]
  - pytube [required: >=12.1.0,<13.0.0, installed: 12.1.3]
  - ytmusicapi [required: >=0.22.0,<0.30.0, installed: 0.25.2]
    - requests [required: >=2.22, installed: 2.31.0]
      - certifi [required: >=2017.4.17, installed: 2022.5.18]
      - charset-normalizer [required: >=2,<4, installed: 2.0.12]
      - idna [required: >=2.5,<4, installed: 3.3]
      - urllib3 [required: >=1.21.1,<3, installed: 2.1.0]

lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by eugenweissbart** [comment]
Here's what I did:  
1. Go to `/usr/local/lib/python3.9/dist-packages/`
2. In this directory, apart from `mopidy_ytmusic` there should be `mopidy_ytmusic-0.3.8.dist-info`. Go inside and open `METADATA` with your favourite editor  
3. Find a line which says `Requires-Dist: ytmusicapi (>=0.22.0,<0.30.0)` and make it look like `Requires-Dist: ytmusicapi (>=0.22.0)`
4. Save your changes  
5. Run `pip install ytmusicapi==1.7.3` to upgrade ytmusicapi to latest version  
6. Restart mopidy

Seems working well so far
